[package]
name = "highlighter"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
# arborium = { version = "2.4.3", features = ["all-languages"] }
napi = "3.7.1"
napi-derive = "3.4.1"
tree-sitter = "0.26.3"
tree-sitter-bash = "0.25.1"
tree-sitter-highlight = "0.26.3"
tree-sitter-javascript = "0.25.0"
tree-sitter-python = "0.25.0"
tree-sitter-typescript = "0.23.2"
tree-sitter-nix = "0.3.0"
regex = "1.12.2"
const_format = "0.2.35"

[build-dependencies]
cc = "1"
napi-build = "2"

[profile.release]
strip = "symbols"
lto = true
